"""add must_change_password to admin_user

Revision ID: 836d7d1556d9
Revises: 75a831b2af24
Create Date: 2026-05-27 14:30:59.424880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836d7d1556d9'
down_revision = '75a831b2af24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
